### ISSUE TITLE
Unusable after attempting to insert image

### ISSUE THREAD

**Issue by rpglover64** [dmgerman/xournal#26]
After clicking on the insert image icon, _all_ clicks, including those to menus are interpreted as attempts to insert an image.

**Comment by eages** [comment]
I can confirm this on the "next" branch. I'm new to the project and using C code but here's what I've observed so far:

To reproduce:
1. Click on insert image icon (as in OP).
2. Click on the canvas.
3. Cancel or choose an image.
4. Clicking anywhere within the main widget respawns the image dialog.

I compiled with INPUT_DEBUG and saw that clicks after step 3 have debug messages just like canvas events -- even reporting negative vertical values. In contrast, all other tools only report canvas events on the canvas itself.

**Comment by rpglover64** [comment]
I've found a "workaround" (for people who wish to use the "next" branch until this gets fixed): <kbd>Ctrl-Shift-P</kbd> (or any other keyboard command to switch tools).

**Comment by dmgerman** [comment]
Thanks everybody, i haven't had time to look into it, but I will next week.

**Comment by dmgerman** [comment]
Update. This is an upstream issue and Denis is looking into it.

**Comment by dmgerman** [comment]
This issue was fixed by Denis upstream. I have integrated his changes in all my branches, but I haven't had time to do much testing.
